# Generated by Django 3.2.4 on 2021-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('notify', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], default='email', max_length=100)),
            ],
        ),
    ]
